Name: Nurkholis\
Source: Datacamp

# Python Basics

An introduction to the basic concepts of Python. Learn how to use Python interactively and by using a script. Create your first variables and acquaint yourself with Python&apos;s basic data types.

## When to use Python?

Python is a flexible language. For which applications can you use Python?

a. For quick calculations.
b. Develop a database-driven website.
c. Clean and analyze data.
d. $\color{blue}{\text{All of the above.}}$

## Any comments?

You can also add comments to your Python scripts. Comments are important to make sure that you and others can understand what your code is about and do not run as Python code.

They start with $\color{blue}{\text{\#}}$ tag. See the comment in the editor, $\color{blue}{\text{\# Division}}$; now it's your turn to add a comment!

In [1]:
# Division
print(5 / 8)
# Addition
print(7 + 10)

0.625
17


## Python as a calculator

Python is perfectly suited to do basic calculations. It can do $\color{blue}{\text{addition}}$, $\color{blue}{\text{subtraction}}$, $\color{blue}{\text{multiplication}}$, $\color{blue}{\text{division}}$.

In [2]:
# Addition
print ( 4 + 5 )

# Subtraction
print (5 - 5)

# Multiplication
print(3*5)

# Division
print(10/2)

9
0
15
5.0


## Variable

- Specific, case-sensitive name
- Call up value through variable name
- 1.79 m - 68.7 kg

In [3]:
height = 1.79
weight = 68.7
height

1.79

## Variable Assignment

In Python, a variable allows you to refer to a value with a name. To create a variable x with a value of 5, you use $\color{blue}{\text{=}}$, like this example:

x $\color{blue}{\text{=}}$ 5

You can now use the name of this variable, x, instead of the actual value, 5.\
Remember, $\color{blue}{\text{=}}$ in Python means $\color{blue}{\text{assignment}}$, it $\color{black}{\text{doesn't}}$ test equality!

In [4]:
# Create a variable savings
savings = 100

# Print out savings
print(savings)

100


## Calculations with variables

You've now created a $\color{blue}{\text{savings variable}}$, so let's start saving!

Instead of calculating with the actual values, you can use variables instead. The $\color{blue}{\text{savings}}$ variable you created in the previous exercise with a value of $\color{blue}{\text{\$100}}$ is available to you.

How much money would you have saved four months from now, if you saved $\color{blue}{\text{\$10}}$ each month?

In [5]:
# Create the variables monthly_savings and num_months
monthly_savings = 10
num_months = 4

# Multiply monthly_savings and num_months
new_savings = monthly_savings * num_months

# Add new_savings to your savings
total_savings = new_savings + savings

# Print total_savings
print(total_savings)

140


## Other variable types

In the previous exercise, you worked with the integer Python data type:

- $\color{blue}{\text{int}}$, or integer: a number without a fractional part. savings, with the value 100, is an example of an integer.

Next to numerical data types, there are $\color{blue}{\text{three}}$ other very common data types:

- $\color{blue}{\text{float}}$, or floating point: a number that has both an integer and fractional part, separated by a point. $\color{blue}{\text{1.1}}$, is an example of a float.
- $\color{blue}{\text{str}}$, or string: a type to represent text. You can use single or double quotes to build a string.
- $\color{blue}{\text{bool}}$, or boolean: a type to represent logical values. It can only be $\color{blue}{\text{True}}$ or $\color{blue}{\text{False}}$ (the capitalization is important!).

In [6]:
# Create a variable half
half = 0.5

# Create a variable intro
intro = "Hello! How are you?"

# Create a variable is_good
is_good = True

# print half, intro, and is_good
print("half=", half, "\nintro:", intro, "\nis good? ", is_good)

half= 0.5 
intro: Hello! How are you? 
is good?  True


## Guess the type

To find out the type of a value or $\color{blue}{\text{a}}$ variable that refers to that value, you can use the $\color{blue}{\text{type()}}$ function. Suppose you've defined a variable $\color{blue}{\text{a}}$, but you forgot the type of this variable. To determine the type of $\color{blue}{\text{a}}$, simply execute:

$\color{blue}{\text{type(a)}}$

In [7]:
# Create a variable half
half = 0.5

# Create a variable intro
intro = "Hello! How are you?"

# Create a variable is_good
is_good = True

# print type half, intro, and is_good
print("half", type(half), "\nintro", type(intro), "\nis_good?", type(is_good))

half <class 'float'> 
intro <class 'str'> 
is_good? <class 'bool'>


## Operations with other types

$\color{blue}{\text{different types}}$ $\color{black}{\text{behave}}$ $\color{blue}{\text{differently}}$ in Python.

When you $\color{blue}{\text{sum two strings}}$, for example, you'll get $\color{black}{\text{different behavior}}$ than when you $\color{blue}{\text{sum two integers}}$ or $\color{blue}{\text{two booleans}}$.

In [8]:
monthly_savings = 10
num_months = 12
intro = "Hello! How are you?"
is_good = True

# Calculate year_savings using monthly_savings and num_months
year_savings = monthly_savings*num_months

# Print the type of year_savings
print(type(year_savings))

# Assign sum of intro and intro to doublenum_months (numbers)
doublenum_months = num_months + num_months

# Print out doubleis_good
print('doublenum_months = ', doublenum_months)

# Assign sum of intro and intro to doubleintro (string)
doubleintro = intro + intro

# Print out doubleintro
print('doubleintro = ', doubleintro)

# Assign sum of intro and intro to doubleis_good (Boolean)
doubleis_good = is_good + is_good

# Print out doubleis_good
print('doubleis_good = ', doubleis_good)

<class 'int'>
doublenum_months =  24
doubleintro =  Hello! How are you?Hello! How are you?
doubleis_good =  2


## Type conversion

Using the $\color{blue}{\text{+}}$ operator to paste together two strings can be very useful in building custom messages.

Suppose, for example, that you've calculated your savings want to summarize the results in a string.

To do this, you'll need to explicitly convert the types of your variables. More specifically, you'll need str(), to convert a value into a string. $\color{blue}{\text{str(savings)}}$, for example, will convert the integer $\color{blue}{\text{savings}}$ to a string.

Similar functions such as $\color{blue}{\text{int()}}$, $\color{blue}{\text{float()}}$ and $\color{blue}{\text{bool()}}$.

In [9]:
# Definition of savings and total_savings
savings = 100
total_savings = 150

# Fix the printout
print("I started with $" + str(savings) + " and now have $" + str(total_savings) + ". Awesome!")

# Definition of pi_string
pi_string = "3.1415926"

# Convert pi_string into float: pi_float
pi_float = float(pi_string)

# print pi_float and type of pi_float
print("pi_float = ", pi_float, type(pi_float))

I started with $100 and now have $150. Awesome!
pi_float =  3.1415926 <class 'float'>


## Can Python handle everything?

Now that you know something more about combining different sources of information, have a look at the four Python expressions below. Which one of these will throw an error?

a. "I can add integers, like " + str(5) + " to strings."
b. "I said " + ("Hey " * 2) + "Hey!"
c. $\color{blue}{\text{"The correct answer to this multiple choice exercise is answer number " + 2}}$
d. True + False

$\color{green}{\text{Because you're not converting 2 to a string with str(), this will give an error.}}$

# Python Lists

Learn to $\color{green}{\text{store}}$, $\color{green}{\text{access}}$, and $\color{green}{\text{manipulate data}}$ in $\color{black}{\text{lists}}$: the first step toward efficiently working with huge amounts of data.

## Create a list

$\color{red}{\text{As opposed}}$ to int, bool etc., a $\color{blue}{\text{list}}$ is a $\color{black}{\text{compound data type}}$; you can $\color{blue}{\text{group values}}$ together:

In [10]:
a = "is"
b = "nice"
my_list = ["my", "list", a, b]

print(a)
print(b)
print(my_list)

is
nice
['my', 'list', 'is', 'nice']


After measuring the height of your family, you decide $\color{blue}{\text{to collect}}$ some information on $\color{blue}{\text{the house}}$  you're living in. The areas of the different parts of your house are stored in separate variables for now, as shown in the script.

In [11]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall, kit, liv, bed, bath]

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


## Create list with different types

A list can contain any Python type. Although it's not really common, a list can also contain a mix of Python types including strings, floats, booleans, etc.

The printout of the previous exercise wasn't really satisfying. It's just a list of numbers representing the areas, but you can't tell which area corresponds to which part of your house.

The code in the editor is the start of a solution. For some of the areas, the name of the corresponding room is already placed in front. Pay attention here! $\color{green}{\text{"bathroom"}}$ is a $\color{blue}{\text{string}}$, while $\color{green}{\text{bath}}$ is a variable that represents the $\color{blue}{\text{float 9.50}}$ you specified earlier.

In [12]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


## Select the valid list

A list can contain any Python type. But a list itself is also a Python type. That means that a list can also contain a list! Python is getting funkier by the minute, but fear not, just remember the list syntax:

my_list = [el1, el2, el3]

Can you tell which ones of the following lines of Python code are valid ways to build a list?

A. [1, 3, 4, 2]\
B. [[1, 2, 3], [4, 5, 7]]\
C. [1 + 2, "a" * 5, 3]

$\color{black}{\text{Possible Answer:}}$\
- $\color{green}{\text{A, B, and C}}$\
- B\
- B and C\
- C

## List of lists

As a data scientist, you'll often be dealing with a lot of data, and it will make sense to group some of this data.

Instead of creating a flat list containing strings and floats, representing the names and areas of the rooms in your house, you can create a list of lists. The script in the editor can already give you an idea.

Don't get confused here: $\color{green}{\text{"hallway"}}$ is a $\color{blue}{\text{string}}$, while $\color{green}{\text{hall}}$ is a variable that represents the $\color{blue}{\text{float 11.25}}$ you specified earlier.

In [13]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]

# Print out house
print(house)

# Print out the type of house
print(type(house))

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


## Subset and conquer

Subsetting Python lists is a piece of cake. Take the code sample below, which creates a list $\color{blue}{\text{x}}$ and then $\color{blue}{\text{selects "b"}}$ from it. Remember that this is the $\color{green}{\text{second element}}$, so it has $\color{green}{\text{index 1}}$. You can also use negative indexing.

In [14]:
x = ["a", "b", "c", "d"]
print(x[1], x[-3]) # same result!

b b


Remember the $\color{green}{\text{areas}}$ list from before, containing both strings and floats? Its definition is already in the script.

In [15]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])

11.25
9.5
20.0


## Subset and calculate

After you've extracted values from a list, you can use them to perform additional calculations. Take this example, where the second and fourth element of a list $\color{blue}{\text{x}}$ are extracted. The strings that result are pasted together using the $\color{blue}{\text{+}}$ operator:

In [16]:
x = ["a", "b", "c", "d"]
print(x[1] + x[3])

bd


In [17]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[3] + areas[7]

# Print the variable eat_sleep_area
print("eat_sleep_area = ", "areas kitchen + areas bedroom = ", areas[3], " + ", areas[7], " = ", eat_sleep_area)

eat_sleep_area =  areas kitchen + areas bedroom =  18.0  +  10.75  =  28.75


## Slicing and dicing

Selecting single values from a list is just one part of the story. It's also possible to slice your list, which means selecting multiple elements from your list. Use the following syntax:

my_list[$\color{green}{\text{start}}$:$\color{red}{\text{end}}$]

The $\color{green}{\text{start}}$ index will be $\color{black}{\text{included}}$, while the $\color{red}{\text{end}}$ index is $\color{black}{\text{not}}$.

The code sample below shows an example. A list with $\color{black}{\text{"b"}}$ and $\color{black}{\text{"c"}}$, corresponding to indexes 1 and 2, are selected from a list $\color{blue}{\text{x}}$:

In [18]:
x = ["a", "b", "c", "d"]
x[1:3]

['b', 'c']

The elements with index $\color{green}{\text{1 and 2}}$ are $\color{black}{\text{included}}$, while the element with index $\color{red}{\text{3}}$ is $\color{black}{\text{not}}$.

In [19]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[0:6]

# Use slicing to create upstairs
upstairs = areas[-4:]

# Print out downstairs and upstairs
print("downstairs \t= ", downstairs, "\nupstairs \t= ", upstairs)

downstairs 	=  ['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0] 
upstairs 	=  ['bedroom', 10.75, 'bathroom', 9.5]


## Slicing and dicing (2)

the syntax where you specify both where to begin and end the slice of your list:

my_list[$\color{green}{\text{begin}}$:$\color{red}{\text{end}}$]

However, it's also possible not to specify these indexes. If you don't specify the $\color{green}{\text{begin}}$ index, Python figures out that you want to start your slice at the beginning of your list. If you don't specify the $\color{red}{\text{end}}$ index, the slice will go all the way to the last element of your list.

In [20]:
x = ["a", "b", "c", "d"]
print("x[:2] \t=", x[:2], "\nx[2:] \t=", x[2:], "\nx[:] \t=",  x[:])

x[:2] 	= ['a', 'b'] 
x[2:] 	= ['c', 'd'] 
x[:] 	= ['a', 'b', 'c', 'd']


Create $\color{blue}{\text{downstairs}}$ again, as the $\color{red}{\text{first 6 elements}}$ of areas. This time, simplify the slicing by omitting $\color{black}{\text{the begin index.}}$

In [21]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Alternative slicing to create downstairs with first 6 elements of areas
downstairs = areas[:6]

# print slicing to create downstairs with first 6 elements of areas
print("downstairs \t= ", downstairs)

downstairs 	=  ['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]


Create $\color{blue}{\text{upstairs}}$ again, as the $\color{red}{\text{last 4 elements}}$ of areas. This time, simplify the slicing by omitting $\color{black}{\text{the end index.}}$

In [22]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Alternative slicing to create upstairs with last 4 elements
upstairs = areas[-4:]

# print slicing to create upstairs with last 4 elements
print("upstairs \t= ", upstairs)

upstairs 	=  ['bedroom', 10.75, 'bathroom', 9.5]


## Subsetting lists of lists

You saw before that a Python list can contain practically anything; even other lists! To subset lists of lists, you can use the same technique as before: square brackets.

In [23]:
x = [["a", "b", "c"],
     ["d", "e", "f"],
     ["g", "h", "i"]]
print("x[2][0] \t= ", x[2][0], "\nx[2][:2] \t=" ,x[2][:2])

x[2][0] 	=  g 
x[2][:2] 	= ['g', 'h']


$\color{blue}{\text{x[2]}}$ results in a list, that you can $\color{red}{\text{subset again}}$ by adding $\color{black}{\text{additional}}$ square brackets.

What will $\color{blue}{\text{house[-1][1]}}$ return? $\color{blue}{\text{house}}$, the list of lists that you created before, is already defined for you in the workspace.

In [24]:
# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]
print("house[-1][0] = ", house[-1][0], "\nhouse[-1][1] = ", house[-1][1])

house[-1][0] =  bathroom 
house[-1][1] =  9.5


$\color{black}{\text{Possible answers:}}$ \
- A float: the kitchen area \
- A string: "kitchen" \
- $\color{blue}{\text{A float: the bathroom area}}$ \
- A string: "bathroom"

## Replace list elements

Replacing list elements is pretty easy. Simply subset the list and assign new values to the subset. You can select single elements or you can change entire list slices at once.

Can you tell $\color{black}{\text{what's}}$ happening and $\color{black}{\text{why}}$?

In [25]:
x = ["a", "b", "c", "d"]
x[1] = "r"
x

['a', 'r', 'c', 'd']

In [26]:
x = ["a", "b", "c", "d"]
x[1] = "r"
x[2:] = ["s", "t"]
x

['a', 'r', 's', 't']

For this and the following exercises, you'll continue working on the $\color{blue}{\text{areas}}$ list that contains the names and areas of different rooms in a house.

In [27]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area
areas[-1] = 10.50

# Change "living room" to "chill zone"
areas[4] = "chill zone"

# print areas and areas[4]
print("areas \t\t= " , areas, "\nareas[4] \t= " , areas[4])

areas 		=  ['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5] 
areas[4] 	=  chill zone


## Extend a list

If you can change elements in a list, you sure want to be able to add elements to it, right? You can use the $\color{blue}{\text{+}}$ operator:

In [28]:
x = ["a", "b", "c", "d"]
y = x + ["e", "f"]
y

['a', 'b', 'c', 'd', 'e', 'f']

You just won the lottery, awesome! You decide to build a poolhouse and a garage. Can you add the information to the $\color{blue}{\text{areas}}$ list?

- Use the $\color{blue}{\text{+}}$ operator to paste the list $\color{green}{\text{["poolhouse", 24.5]}}$ to the end of the $\color{blue}{\text{areas}}$ list. Store the resulting list as $\color{green}{\text{areas\_1}}$.
- Further extend $\color{green}{\text{areas\_1}}$ by adding data on your garage. Add the string $\color{green}{\text{"garage"}}$ and float $\color{green}{\text{15.45}}$. Name the resulting list $\color{green}{\text{areas\_2}}$.

In [29]:
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse", 24.5]

# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage", 15.45]

# print areas_1 and areas_2
print("areas_1 \t= ", areas_1,"\nareas_2 \t= ", areas_2)

areas_1 	=  ['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5] 
areas_2 	=  ['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]


## Delete list elements

Finally, you can also remove elements from your list. You can do this with the $\color{blue}{\text{del}}$ statement:

In [30]:
x = ["a", "b", "c", "d"]
del(x[1])
x

['a', 'c', 'd']

Pay attention here: as soon as you remove an element from a list, the indexes of the elements that come after the deleted element all change!

The updated and extended version of $\color{blue}{\text{areas}}$ that you've built in the previous exercises is coded below.

In [31]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

There was a mistake! The amount you won with the lottery is not that big after all and it looks like the poolhouse isn't going to happen. You decide to remove the corresponding string and float from the $\color{blue}{\text{areas}}$ list.

The $\color{green}{\text{;}}$ sign is used to place commands on the same line. The following two code chunks are equivalent:

$\color{blue}{\text{Same line: }}$ \
- command1; command2

$\color{blue}{\text{Separate lines:}}$ \
- command1 \
- command2

Which of the code chunks will do the job for us?

$\color{black}{\text{Possible answers:}}$

- del(areas[10]); del(areas[11])
- del(areas[10:11])
- $\color{blue}{\text{del(areas[-4:-2])}}$
- del(areas[-3]); del(areas[-4])

In [32]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

# delete areas[10] or poolhouse;
# delete areas[11] after areas[10] has been deleted or garage (index 12 become index 11)
del(areas[10]); del(areas[11])

# print del(areas[10]); del(areas[11]) -> String poolhouse and garage has been deleted.
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 24.5, 15.45]


In [33]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

# delete areas[10:11] or just area[10] or poolhouse;
del(areas[10:11])

# print del(areas[10:11]) -> String poolhouse has been deleted
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 24.5, 'garage', 15.45]


In [34]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

# delete areas[-4:-2] or just area[-4] and area[-3] or poolhouse and float 24.5;
del(areas[-4:-2])

# print del(areas[-4:-2]) -> String poolhouse and float 24.5 has been deleted
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'garage', 15.45]


In [35]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

# delete areas[-3] or float 24.5;
# delete areas[-4] after areas[-3] has been deleted or float 10.50 (index -5 become index -4)
del(areas[-3]); del(areas[-4])

# print del(del(areas[-3]); del(areas[-4])) -> float 24.5 and float 10.50 has been deleted
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 'poolhouse', 'garage', 15.45]


## Inner workings of lists

How Python lists work behind the scenes. In this exercise you'll get some hands-on experience with this.

The Python code in the script already creates a list with the name $\color{blue}{\text{areas}}$ and a copy named $\color{green}{\text{areas\_copy}}$. Next, the first element in the $\color{green}{\text{areas\_copy}}$ list is changed and the $\color{blue}{\text{areas}}$ list is printed out. If you hit Run Code you'll see that, although you've changed $\color{green}{\text{areas\_copy}}$, the change also takes effect in the $\color{blue}{\text{areas}}$ list. That's because $\color{blue}{\text{areas}}$ and $\color{green}{\text{areas\_copy}}$ point to the same list.

If you want to prevent changes in $\color{green}{\text{areas\_copy}}$ from also taking effect in $\color{blue}{\text{areas}}$, you'll have to do a more explicit copy of the $\color{blue}{\text{areas}}$ list. You can do this with $\color{blue}{\text{list()}}$ or by using $\color{green}{\text{[:]}}$.

In [36]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy = areas

# Change areas_copy
areas_copy[0] = 5.0

# Print areas. So, float 11.25 will be changed become float 5.0 in the areas variable
print(areas)

[5.0, 18.0, 20.0, 10.75, 9.5]


In [37]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy with areas[:] or list(areas)
areas_copy = areas[:]

# Change areas_copy
areas_copy[0] = 5.0

# Print areas. The areas aren't changed 
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


# Functions and Packages

You'll learn how to use functions, methods, and packages to efficiently leverage the code that brilliant Python developers have written. The goal is to reduce the amount of code you need to solve challenging problems!

## Familiar functions

Out of the box, Python offers a bunch of built-in functions to make your life as a data scientist easier. You already know two such functions: $\color{green}{\text{print()}}$ and $\color{green}{\text{type()}}$. You've also used the functions $\color{green}{\text{str()}}$, $\color{green}{\text{int()}}$, $\color{green}{\text{bool()}}$ and $\color{green}{\text{float()}}$ to switch between data types. These are built-in functions as well.

Calling a function is easy. To get the type of $\color{blue}{\text{3.0}}$ and store the output as a new variable, $\color{blue}{\text{result}}$, you can use the following:

In [38]:
result = type(3.0)

The general recipe for calling functions and saving the result to a variable is thus:

output = $\color{green}{\text{function\_name}}$($\color{blue}{\text{input}}$)

In [39]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print("var_1 -> type", type(var1))

# Print out length of var1 -> total list on the var1
print("length var1 is ", len(var1))

# Convert var2 to an integer: out2 ->integer True is 1; integer False is 0.
out2 = int(var2)
print("integer out2 is ", out2)

var_1 -> type <class 'list'>
length var1 is  4
integer out2 is  1


## Help!

Maybe you already know the name of a Python function, but you still have to figure out how to use it. Ironically, you have to ask for information about a function with another function: $\color{blue}{\text{help()}}$.

To get help on the $\color{blue}{\text{max()}}$ function, for example, you can use one of these calls:

In [40]:
#help(max) or ?max
help(max)


Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [41]:
#help(max) or ?max
?max

Docstring:
max(iterable, *[, default=obj, key=func]) -> value
max(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its biggest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more arguments, return the largest argument.
Type:      builtin_function_or_method

Open up the documentation on $\color{blue}{\text{pow()}}$. Which of the following statements is true?

$\color{black}{\text{Possible answers:}}$ \
- $\color{blue}{\text{pow()}}$ takes three arguments: $\color{green}{\text{base}}$, $\color{green}{\text{exp}}$, and $\color{green}{\text{mod}}$. If you don't specify $\color{green}{\text{mod}}$, the function will return an error. \
- $\color{blue}{\text{pow()}}$ takes three arguments: $\color{green}{\text{base}}$, $\color{green}{\text{exp}}$, and $\color{green}{\text{None}}$. All of these arguments are required. \
- $\color{blue}{\text{pow()}}$ $\color{red}{\text{takes three arguments:}}$ $\color{green}{\text{base}}$, $\color{green}{\text{exp}}$, $\color{red}{\text{and}}$ $\color{green}{\text{mod}}$. $\color{green}{\text{base}}$ $\color{red}{\text{and}}$ $\color{green}{\text{exp}}$ $\color{red}{\text{are required arguments}}$, $\color{green}{\text{mod}}$ $\color{red}{\text{is an optional argument}}$. \
- $\color{blue}{\text{pow()}}$ takes two arguments: $\color{green}{\text{exp}}$ and $\color{green}{\text{mod}}$. If you don't specify $\color{green}{\text{exp}}$, the function will return an error.

## Multiple arguments

In the previous exercise, you identified optional arguments by viewing the documentation with $\color{blue}{\text{help()}}$. You'll now apply this to change the behavior of the $\color{blue}{\text{sorted()}}$ function.

Have a look at the documentation of $\color{blue}{\text{sorted()}}$ by typing $\color{blue}{\text{help(sorted)}}$.

You'll see that $\color{blue}{\text{sorted()}}$ takes three arguments: $\color{green}{\text{iterable}}$, $\color{green}{\text{key}}$, and $\color{green}{\text{reverse}}$.

$\color{green}{\text{key=None}}$ means that if you don't specify the $\color{green}{\text{key}}$ argument, it will be $\color{green}{\text{None}}$. $\color{green}{\text{reverse=False}}$ means that if you don't specify the $\color{green}{\text{reverse}}$ argument, it will be $\color{green}{\text{False}}$, by default.

In this exercise, you'll only have to specify $\color{green}{\text{iterable}}$ and $\color{green}{\text{reverse}}$, not $\color{green}{\text{key}}$. The first input you pass to $\color{blue}{\text{sorted()}}$ will be matched to the $\color{green}{\text{iterable}}$ argument, but what about the second input? To tell Python you want to specify $\color{green}{\text{reverse}}$ without changing anything about $\color{green}{\text{key}}$, you can use $\color{green}{\text{=}}$ to assign it a new value:

$\color{green}{\text{sorted}}$(...., reverse=....)

Two lists have been created for you. Can you paste them together and sort them in descending order?

$\color{black}{\text{Note:}}$ For now, we can understand an $\color{red}{\text{iterable}}$ as being any collection of objects, e.g., a List.

In [42]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second

# Sort full in descending order: full_sorted
full_sorted = sorted(full, reverse = True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


## String Methods

Strings come with a bunch of methods. Follow the instructions closely to discover some of them. If you want to discover them in more detail, you can always type $\color{blue}{\text{help(str)}}$.

A string $\color{green}{\text{place}}$ has already been created for you to experiment with.

In [43]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place: place_up
place_up = place.upper()

# Print out place and place_up
print("string-place \t:", place)
print("upper-place \t:", place_up)

# Print out the number of o's in place
print("the number of o's in place :", place.count("o"))

string-place 	: poolhouse
upper-place 	: POOLHOUSE
the number of o's in place : 3


## List Methods

Strings are not the only Python types that have methods associated with them. Lists, floats, integers and booleans are also types that come packaged with a bunch of useful methods. In this exercise, you'll be experimenting with:

- $\color{blue}{\text{index()}}$, to get the index of the first element of a list that matches its input and
- $\color{blue}{\text{count()}}$, to get the number of times an element appears in a list.

You'll be working on the list with the area of different parts of a house: $\color{blue}{\text{areas.}}$

In [44]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print("The number index of 20.0 in areas variable is", areas.index(20.0))

# Print out how often 9.50 appears in areas
print("The total count of 9.5 in areas variable is", areas.count(9.50))

The number index of 20.0 in areas variable is 2
The total count of 9.5 in areas variable is 1


## List Methods (2)

Most list methods will change the list they're called on. Examples are:

- $\color{blue}{\text{append()}}$, that adds an element to the list it is called on,
- $\color{blue}{\text{remove()}}$, that removes the first element of a list that matches the input, and
- $\color{blue}{\text{reverse()}}$, that reverses the order of the elements in the list it is called on.

You'll be working on the list with the area of different parts of the house: $\color{blue}{\text{areas.}}$

In [45]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5); areas.append(15.45)


# Print out areas before reverse
print("areas after append with new elements of 24.5 and 15.45 is", areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print("areas after reverse is", areas)

areas after append with new elements of 24.5 and 15.45 is [11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
areas after reverse is [15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


## Import package

As a data scientist, some notions of geometry never hurt. Let's refresh some of the basics.

For a fancy clustering algorithm, you want to find the circumference, $\color{red}{\text{C}}$, and area, $\color{red}{\text{A}}$, of a circle. When the radius of the circle is $\color{red}{\text{r}}$, you can calculate 
$\color{red}{\text{C}}$ and $\color{red}{\text{A}}$ as:

- C = 2 * pi * r \
- A = pi * r**2

In Python, the symbol for exponentiation is $\color{red}{\text{**}}$. This operator raises the number to its left to the power of the number to its right. For example $\color{red}{\text{3**}}$$\color{blue}{\text{4}}$ is $\color{red}{\text{3}}$ to the power of $\color{blue}{\text{4}}$ and will give 81.

To use the constant $\color{red}{\text{pi}}$, you'll need the $\color{green}{\text{math}}$ package. A variable $\color{red}{\text{r}}$ is already coded in the script. Fill in the code to calculate $\color{red}{\text{C}}$ and $\color{red}{\text{A}}$ and see how the $\color{blue}{\text{print()}}$ functions create some nice printouts.

In [46]:
# Import the math package
import math

# Definition of radius
r = 0.43

# Calculate C
C = 2 * math.pi * r

# Calculate A
A = math.pi * r**2

# Build printout
# notice that C and A variable is string not float.
print("Circumference\t: " + str(C)) 
print("Area\t\t: " + str(A)) 

Circumference	: 2.701769682087222
Area		: 0.5808804816487527


## Selective Import

General imports, like $\color{blue}{\text{import math}}$, make all functionality from the $\color{green}{\text{math package}}$ available to you. However, if you decide to only use a specific part of a package, you can always make your import more selective:

In [47]:
from math import pi

Let's say the Moon's orbit around planet Earth is a perfect circle, with a radius $\color{red}{\text{r}}$ (in km) that is defined in the script.

In [48]:
# Import radians function of math package
from math import radians

# Definition of radius
r = 192500

# Travel distance of Moon over 12 degrees. Store in dist.
dist = r * radians(12)

# Print out dist
print("Travel distance of Moon over 12 degrees is "+ str(dist) + " km.")

Travel distance of Moon over 12 degrees is 40317.10572106901 km.


## Different ways of Importing

There are several ways to import packages and modules into Python. Depending on the import call, you'll have to use different Python code.

Suppose you want to use the function $\color{blue}{\text{inv()}}$, which is in the $\color{green}{\text{linalg}}$ subpackage of the scipy package. You want to be able to use this function as follows:

**my_inv([[1,2], [3,4]])**

Which import statement will you need in order to run the above code without an error?

**Possible answers:** \
- import scipy \
- import scipy.linalg \
- from scipy.linalg import my_inv \
- **from scipy.linalg import inv as my_inv**

# NumPy

NumPy is a fundamental Python package to efficiently practice data science. Learn to work with powerful tools in the NumPy array, and get started with data exploration.

## Your First NumPy Array

In this chapter, we're going to dive into the world of baseball. Along the way, you'll get comfortable with the basics of $\color{blue}{\text{numpy}}$, a powerful package to do data science.

A **list baseball** has already been defined in the Python script, representing the height of some baseball players in centimeters. Can you add some code here and there to create a $\color{blue}{\text{numpy}}$ array from it?

In [49]:
# Import the numpy package as np
import numpy as np

# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print("List baseball with numpy array\t:", np_baseball,
      "\ntype\t\t\t\t:", type(np_baseball))

List baseball with numpy array	: [180 215 210 210 188 176 209 200] 
type				: <class 'numpy.ndarray'>


## Baseball players' height

You are a huge baseball fan. You decide to call the MLB (Major League Baseball) and ask around for some more statistics on the height of the main players. They pass along data on more than a thousand players, which is stored as a regular Python list: $\color{blue}{\text{height\_in}}$. The height is expressed in inches. Can you make a $\color{blue}{\text{numpy}}$ array out of it and convert the units to meters?

$\color{blue}{\text{height\_in}}$ is already available and the numpy package is loaded, so you can start straight away (Source: <a href="https://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_MLB_HeightsWeights" target="_blank" rel="noopener noreferrer">$\color{blue}{\text{stat.ucla.edu}}$</a>).

In [50]:
#import pandas
import pandas as pd

# Import numpy
import numpy as np

# Read the CSV file
baseball_csv = pd.read_csv("baseball.csv")

# create np_baseball_csv as numpy arrays
np_baseball_csv = np.array(baseball_csv)

# Read just the list height.
height_in = np_baseball_csv[:, 3]

# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in 
print("baseball player height (in inches):", np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254

# Convert np_height_m with int function to float function: np_height_m_float
np_height_m_float = np_height_m.astype(float)

# Print np_height_m_float
print("baseball player height (in meters):", np.round(np_height_m_float, decimals=2))

baseball player height (in inches): [74 74 72 ... 75 75 73]
baseball player height (in meters): [1.88 1.88 1.83 ... 1.9  1.9  1.85]


## Baseball player's BMI

The MLB also offers to let you analyze their weight data. Again, both are available as regular Python lists: $\color{blue}{\text{height\_in}}$ and $\color{blue}{\text{weight\_lb}}$. $\color{blue}{\text{height\_in}}$ is **in inches** and $\color{blue}{\text{weight\_lb}}$ is **in pounds**.

It's now possible to calculate the BMI of each baseball player.

In [51]:
#import pandas
import pandas as pd

# Import numpy
import numpy as np

# Read the CSV file and just list height and weight
baseball_csv = pd.read_csv("baseball.csv")

# create np_baseball_csv as numpy arrays
np_baseball_csv = np.array(baseball_csv)

# Read just the list height and weight.
height_in = np_baseball_csv[:, 3]
weight_lb = np_baseball_csv[:, 4]

# Create array from height_in with metric units: np_height_m
np_height_m = (np.array(height_in) * 0.0254).astype(float)

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = (np.array(weight_lb) * 0.453592).astype(float)

# Calculate the BMI: bmi
bmi = np.round(np_weight_kg / np_height_m **2, decimals=3)

# Print out bmi
print("BMI of each baseball player:", bmi)

BMI of each baseball player: [23.11  27.604 28.481 ... 25.623 23.748 25.727]


## Lightweight baseball players

To subset both regular Python lists and $\color{blue}{\text{numpy}}$ arrays, you can use square brackets:

In [52]:
x = [4 , 9 , 6, 3, 1]
x[1]

9

In [53]:
x = [4 , 9 , 6, 3, 1]

import numpy as np
y = np.array(x)
y[1]

9

For numpy specifically, you can also use **boolean** $\color{blue}{\text{numpy}}$ arrays:

In [54]:
y = np.array([4 , 9 , 6, 3, 1])
high = y > 5
y[high]

array([9, 6])

Follow the instructions and reveal interesting things from the data! $\color{blue}{\text{height\_in}}$ and $\color{blue}{\text{weight\_lb}}$ are available as regular lists.

In [55]:
#import pandas
import pandas as pd

# Import numpy
import numpy as np

# Read the CSV file and just list height and weight
baseball_csv = pd.read_csv("baseball.csv")
# create np_baseball_csv as numpy arrays
np_baseball_csv = np.array(baseball_csv)

# Calculate the BMI: bmi
np_height_m = (np.array(height_in) * 0.0254).astype(float)
np_weight_kg = (np.array(weight_lb) * 0.453592).astype(float)
bmi = np.round(np_weight_kg / np_height_m ** 2, decimals = 2)

# Create the light array
Light = bmi < 21

# Print out light
print("Boolean light of BMI\t:", Light[True])

# Print out BMIs of all baseball players whose BMI is below 21
print("BMI\t\t\t:", bmi[Light])

Boolean light of BMI	: [[False False False ... False False False]]
BMI			: [20.54 20.54 20.69 20.69 20.34 20.34 20.69 20.16 19.5  20.69 20.92]


## NumPy Side Effects

As Hugo explained before, $\color{blue}{\text{numpy}}$ is great for doing vector arithmetic. If you compare its functionality with regular Python lists, however, some things have changed.

First of all, $\color{blue}{\text{numpy}}$ arrays cannot contain elements with different types. If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. This is known as type coercion.

Second, the typical arithmetic operators, **such as +, -, * and /** have a different meaning for regular Python lists and numpy arrays.

Have a look at this line of code:

In [56]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

Can you tell which code chunk builds the exact same Python object? The $\color{blue}{\text{numpy}}$ package is already imported as $\color{blue}{\text{np}}$, so you can start experimenting in the Python!

**Possible answers:** \
- np.array([True, 1, 2, 3, 4, False]) \
- **np.array([4, 3, 0]) + np.array([0, 2, 2])** \
- np.array([1, 1, 2]) + np.array([3, 4, -1]) \
- np.array([0, 1, 2, 3, 4, 5])

## Subsetting Numpy Arrays

You've seen it with your own eyes: Python lists and $\color{blue}{\text{numpy}}$ arrays sometimes behave differently. Luckily, there are still certainties in this world. For example, subsetting (using the square bracket notation on lists or arrays) works exactly the same. To see this for yourself, try the following lines of code in the Python:

In [57]:
x = ["a", "b", "c"]
x[1]

'b'

In [58]:
import numpy as np
x = ["a", "b", "c"]

np_x = np.array(x)
np_x[1]

'b'

The script in the editor already contains code that imports $\color{blue}{\text{numpy}}$ as $\color{blue}{\text{np}}$, and stores both the height and weight of the MLB players as numpy arrays. $\color{blue}{\text{height\_in}}$ and $\color{blue}{\text{weight\_lb}}$ are available as regular lists.

In [59]:
#import pandas
import pandas as pd

# Import numpy
import numpy as np

# Read the CSV file and just list height and weight
baseball_csv = pd.read_csv("baseball.csv")

# create np_baseball_csv as numpy arrays
np_baseball_csv = np.array(baseball_csv)

# Read just the list height and weight.
height_in = np_baseball_csv[:, 3]
weight_lb = np_baseball_csv[:, 4]

# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 50
print("the weight at index 50\t\t:", np_weight_lb[50])

# Print out sub-array of np_height_in: index 100 up to and including index 110
print("the height at index 100-111\t:", np_height_in[100:111])

the weight at index 50		: 200
the height at index 100-111	: [73 74 72 73 69 72 73 75 75 73 72]


## Your First 2D NumPy Array

Before working on the actual MLB data, let's try to create a 2D $\color{blue}{\text{numpy}}$ array from a small list of lists.

In this exercise, $\color{blue}{\text{baseball}}$ is a list of lists. The main list contains 4 elements. Each of these elements is a list containing the height and the weight of 4 baseball players, in this order. $\color{blue}{\text{baseball}}$ is already coded for you in the script.

In [60]:
# Import numpy
import numpy as np

# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print("type of np_baseball\t:", type(np_baseball))

# Print out the shape of np_baseball
print("shape of np_baseball\t:", np_baseball.shape)

type of np_baseball	: <class 'numpy.ndarray'>
shape of np_baseball	: (4, 2)


## Baseball data in 2D form

You have another look at the MLB data and realize that it makes more sense to restructure all this information in a 2D $\color{blue}{\text{numpy}}$ array. This array should have 1015 rows, corresponding to the 1015 baseball players you have information on, and 2 columns (for height and weight).

The MLB was, again, very helpful and passed you the data in a different structure, a Python list of lists. In this list of lists, each sublist represents the height and weight of a single baseball player. The name of this embedded list is $\color{blue}{\text{baseball}}$.

Can you store the data as a 2D array to unlock $\color{blue}{\text{numpy}}$'s extra functionality? $\color{blue}{\text{baseball}}$ is available as a regular list of lists.

In [61]:
#import pandas
import pandas as pd

# Import numpy
import numpy as np

# Read the CSV file and just list height and weight
baseball_csv = pd.read_csv("baseball.csv")

# create np_baseball_csv as numpy arrays
np_baseball_csv = np.array(baseball_csv)

# Create and Read the list combined of height and weight: np_baseball
np_baseball = np_baseball_csv[:, 3:5]

# Print out the shape of np_baseball
print("shape of np_baseball:", np_baseball.shape)

shape of np_baseball: (1015, 2)


## Subsetting 2D NumPy Arrays

If your 2D $\color{blue}{\text{numpy}}$ array has a regular structure, i.e. each row and column has a fixed number of values, complicated ways of subsetting become very easy. Have a look at the code below where the elements $\color{red}{\text{"a"}}$ and $\color{red}{\text{"c"}}$ are extracted from a **list of lists**.

In [62]:
# regular list of lists
x = [["a", "b"], ["c", "d"]]
[x[0][0], x[1][0]]

['a', 'c']

In [63]:
# regular list of lists
x = [["a", "b"], ["c", "d"]]

# numpy
import numpy as np
np_x = np.array(x)
np_x[:, 0]

array(['a', 'c'], dtype='<U1')

For regular Python lists, this is a real pain. For 2D $\color{blue}{\text{numpy}}$ arrays, however, it's pretty intuitive! The indexes before the comma refer to the rows, while those after the comma refer to the columns. The $\color{blue}{\text{:}}$ is for slicing; in this example, it tells Python to include all rows.

The code that converts the pre-loaded $\color{blue}{\text{baseball}}$ list to a 2D $\color{blue}{\text{numpy}}$ array is already in the script. The first column contains the players' height in inches and the second column holds player weight, in pounds. Add some lines to make the correct selections. Remember that in Python, the first element is at index 0! $\color{blue}{\text{baseball}}$ is available as a regular list of lists.

In [64]:
#import pandas
import pandas as pd

# Import numpy
import numpy as np

# Read the CSV file and just list height and weight
baseball_csv = pd.read_csv("baseball.csv")

# create np_baseball_csv as numpy arrays
np_baseball_csv = np.array(baseball_csv)

# Create and Read the list of height, weight, and age or 2 columns: np_baseball
np_baseball = np_baseball_csv[:, 3:5]

# Print out the 5th row of np_baseball
print("the 5th row of np_baseball:\n", np_baseball[:5])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:, 1]

# Print out height of 124th player -> The element of 124th is index 123
print("height of 124th player is", np_baseball[123, 0])

the 5th row of np_baseball:
 [[74 180]
 [74 215]
 [72 210]
 [72 210]
 [73 188]]
height of 124th player is 75


## 2D Arithmetic

Remember how you calculated the Body Mass Index for all baseball players? $\color{blue}{\text{numpy}}$ was able to perform all calculations element-wise (i.e. element by element). For 2D $\color{blue}{\text{numpy}}$ arrays this isn't any different! You can combine matrices with single numbers, with vectors, and with other matrices.

Execute the code below in the Python and see if you understand:

In [65]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
np_mat * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [66]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
np_mat + np.array([10, 10])

array([[11, 12],
       [13, 14],
       [15, 16]])

In [67]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
np_mat + np_mat

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

$\color{blue}{\text{np\_baseball}}$ is coded for you; it's again a 2D $\color{blue}{\text{numpy}}$ array with **3 columns** representing **height (in inches)**, **weight (in pounds)** and **age (in years)**.

In [68]:
#import pandas
import pandas as pd

# Import numpy package
import numpy as np

# Read the CSV file and just list height and weight
baseball_csv = pd.read_csv("baseball.csv")

# create np_baseball_csv as numpy arrays
np_baseball_csv = np.array(baseball_csv)

# Create and Read the list of height, weight, and age or 3 columns: np_baseball
np_baseball = (np_baseball_csv[:, 3:6]).astype(float)

# Create numpy array: conversion
conversion = (np.array([0.0254, 0.453592, 1])).astype(float)

# Print out product of np_baseball and conversion
print("baseball 3 columns(height, weight, age) conversion:\n", np.round(np_baseball * conversion, decimals=3))

baseball 3 columns(height, weight, age) conversion:
 [[ 1.88  81.647 22.99 ]
 [ 1.88  97.522 34.69 ]
 [ 1.829 95.254 30.78 ]
 ...
 [ 1.905 92.986 25.19 ]
 [ 1.905 86.182 31.01 ]
 [ 1.854 88.45  27.92 ]]


## Average versus median

You now know how to use $\color{blue}{\text{numpy}}$ functions to get a better feeling for your data. It basically comes down to importing $\color{blue}{\text{numpy}}$ and then calling several simple functions on the $\color{blue}{\text{numpy}}$ arrays:

In [69]:
import numpy as np
x = [1, 4, 8, 10, 12]
np.mean(x)

7.0

In [70]:
import numpy as np
x = [1, 4, 8, 10, 12]
np.median(x)

8.0

The baseball data is available as a 2D $\color{blue}{\text{numpy}}$ array with 3 columns (height, weight, age) and 1015 rows. The name of this $\color{blue}{\text{numpy}}$ array is $\color{blue}{\text{np\_baseball}}$.

In [71]:
#import pandas
import pandas as pd

# Import numpy package
import numpy as np

# Read the CSV file and just list height and weight
baseball_csv = pd.read_csv("baseball.csv")

# create np_baseball_csv as numpy arrays
np_baseball_csv = np.array(baseball_csv)

# Create and Read the list of height, weight, and age or 3 columns: np_baseball
np_baseball = np_baseball_csv[:, 3:6]

# Create np_height_in from np_baseball
np_height_in = np_baseball[:,0]

# Print out the mean of np_height_in
print(np.mean(np_height_in))

# Print out the median of np_height_in
print(np.median(np_height_in))

73.6896551724138
74.0


## Explore the baseball data

Because the mean and median are so far apart, you decide to complain to the MLB. They find the error and send the corrected data over to you. It's again available as a 2D NumPy array $\color{blue}{\text{np\_baseball}}$, with three columns.

The Python script in the editor already includes code to print out informative messages with the different summary statistics. Can you finish the job? $\color{blue}{\text{np\_baseball}}$ is available.

In [72]:
#import pandas
import pandas as pd

# Import numpy package
import numpy as np

# Read the CSV file and just list height and weight
baseball_csv = pd.read_csv("baseball.csv")

# create np_baseball_csv as numpy arrays
np_baseball_csv = np.array(baseball_csv)

# Create and Read the list of height, weight, and age or 3 columns: np_baseball
np_baseball = (np_baseball_csv[:, 3:6]).astype(float)

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average\t\t\t: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median\t\t\t: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation\t: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1])
print("\nCorrelation:\n" + str(corr))

Average			: 73.6896551724138
Median			: 74.0
Standard Deviation	: 2.312791881046546

Correlation:
[[1.         0.53153932]
 [0.53153932 1.        ]]


## Blend it all together

In the last few exercises you've learned everything there is to know about heights and weights of baseball players. Now it's time to dive into another sport: soccer.

You've contacted FIFA for some data and they handed you two lists. The lists are the following:

positions = ['GK', 'M', 'A', 'D', ...]
heights = [191, 184, 185, 180, ...]

Each element in the lists corresponds to a player. The first list, $\color{blue}{\text{positions}}$, contains strings representing each player's position. The possible positions are: $\color{red}{\text{'GK'}}$ (goalkeeper), $\color{red}{\text{'M'}}$ (midfield), $\color{red}{\text{'A'}}$ (attack) and $\color{red}{\text{'D'}}$ (defense). The second list, $\color{blue}{\text{heights}}$, contains integers representing the height of the player in cm. The first player in the lists is a goalkeeper and is pretty tall (191 cm).

You're fairly confident that the median height of goalkeepers is higher than that of other players on the soccer field. Some of your friends don't believe you, so you are determined to show them using the data you received from FIFA and your newly acquired Python skills. $\color{blue}{\text{heights}}$ and $\color{blue}{\text{positions}}$ are available as lists

In [73]:
#import pandas
import pandas as pd

# Import numpy package
import numpy as np

# Read the CSV file and just list height and weight
fifa_csv = pd.read_csv("fifa.csv")

# create np_baseball_csv as numpy arrays
np_fifa_csv = np.array(fifa_csv)

# Create and Read the list of height, weight, and age or 3 columns: np_baseball
np_fifa = np_fifa_csv[:, 3:5]
print("fifa shape\t\t:", np_fifa.shape)
# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = (np_fifa[:,0]).astype(str)
np_heights   = (np_fifa[:,1]).astype(int)

# print : np_positions, np_heights
print("np_positions\t\t:", np_positions)
print("np_heights\t\t:", np_heights)

# because list in np_positions there are white space,
# so we can remove white space with np.char.strip()
# wws = without white space
np_positions_wws = np.char.strip(np_positions)
print("np_positions_wws\t:", np_positions_wws)

# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions_wws == "GK"]

# Heights of the other players: other_heights
other_heights = np_heights[np_positions_wws != "GK"]

# Print out the median height of goalkeepers. Replace 'None'
print("\nMedian height of goalkeepers\t: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players\t: " + str(np.median(other_heights)))

fifa shape		: (8847, 2)
np_positions		: [' GK' ' M' ' A' ... ' D' ' D' ' M']
np_heights		: [191 184 185 ... 183 179 179]
np_positions_wws	: ['GK' 'M' 'A' ... 'D' 'D' 'M']

Median height of goalkeepers	: 188.0
Median height of other players	: 181.0
